apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: acr-pull-secret
spec:
  vault:
    name: KV_NAME # name of key vault
    object:
      name: secret-acr-pull # name of the akv object
      type: secret # akv object type
  output:
    secret:
      name: acr-pull-secret
      type: kubernetes.io/dockerconfigjson
---
apiVersion: spv.no/v2beta1
kind: AzureKeyVaultSecret
metadata:
  name: tls-secret 
spec:
  vault:
    name: KV_NAME # name of key vault
    object:
      name: SECRET NAME
      type: certificate
  output: 
    secret:
      name: NAME OF THE KUBERNETES SECRET # kubernetes secret name
      type: kubernetes.io/tls # kubernetes secret type